### ISSUE TITLE
Recommend using best practices

### ISSUE THREAD

**Issue by jdhitsolutions** [PowerShell/xJea#17]
In looking through some of the code, such as Initalize-Toolkit.ps1 I see a lot of aliases. I'd like to recommend replacing aliases with complete cmdlet names per the community's scripting best practices.

**Comment by johlju** [comment]
This module is deprecated, please use https://github.com/dsccommunity/JeaDsc instead. If this is still an issue in JeaDsc then please open an issue in that repo.
