### ISSUE TITLE
multiple applications 

### ISSUE THREAD

**Issue by nyukers** [PowerShell/xJea#25]
How can I take two external applications with single JEA-config, for example: ipconfig + ping ?

**Comment by gaelcolas** [comment]
You probably should look at [JeaDsc](https://github.com/dsccommunity/JeaDsc) and post your question there (and I'll make a note to archive this repo).

**Comment by johlju** [comment]
Closing this issue as per previous comment. This module is deprecated, please use https://github.com/dsccommunity/JeaDsc instead. If this is still an issue in JeaDsc then please open an issue in that repo.
